#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/sway/scripts/Rofi"
STYLE="default"
RASI="$DIR/Rasi/music.rasi"

# Theme Elements
status="`playerctl status`"
if [[ -z  "$status" ]]; then
	prompt='paucsed'
	mesg="Playerctl controls"
else
	prompt="Playerctl"
	mesg="                                 controls"
fi

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	if [[ ${status} == *"[playing]"* ]]; then
		option_1=" Pause"
	else
		option_1=" Play"
	fi
	option_2=" Stop"
	option_3=" Previous"
	option_4=" Next"
	option_5=" Repeat"
	option_6=" Random"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
fi


# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		playerctl stop
	elif [[ "$1" == '--opt2' ]]; then
		playerctl previous
	elif [[ "$1" == '--opt3' ]]; then
		playerctl play-pause
	elif [[ "$1" == '--opt4' ]]; then
		playerctl next
	elif [[ "$1" == '--opt5' ]]; then
		pamixer -t

	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;

esac
