#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/sway/scripts/Rofi"
STYLE="default"
RASI="$DIR/Rasi/runner.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
